Desktop/Website-Project-Coding/Django_edx_learning/namvt/hello/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("/nam", views.namvt, name="nam"),
    path("<str:name>", views.greet, name="greet"),
    path("", views.index, name="index")
]

Desktop/Website-Project-Coding/Django_edx_learning/namvt/namvt/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hello/', include("hello.urls")),
    path('newyear/', include("newyear.urls")),
    path('task/', include("task.urls")),
]

Desktop/Website-Project-Coding/Django_edx_learning/namvt/newyear/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index")
]

Desktop/Website-Project-Coding/Django_edx_learning/namvt/task/urls.py
from django.urls import path

from . import views

app_name = "task"
urlpatterns = [
    path("", views.index, name="index"),
    path("add", views.add, name="add")
]

Desktop/Website-Project-Coding/Django_edx_learning/namvt/hello/models.py
from django.db import models

# Create your models here.

Desktop/Website-Project-Coding/Django_edx_learning/namvt/newyear/models.py
from django.db import models

# Create your models here.

Desktop/Website-Project-Coding/Django_edx_learning/namvt/task/models.py
from django.db import models

# Create your models here.

Desktop/Website-Project-Coding/Django_edx_learning/namvt/hello/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your tests here.
def index(request):
    return render(request, "hello/index.html")

def namvt(request):
    return HttpResponse("Hello Nam!")

def greet(request, name):
    return render(request, "hello/greet.html", {
        "name" : name.capitalize()
    })

Desktop/Website-Project-Coding/Django_edx_learning/namvt/newyear/views.py
from django.shortcuts import render
from django.http import HttpResponse
import datetime

# Create your views here.
def index(request):
    now = datetime.datetime.now()
    return render(request, "newyear/index.html",{
        "newyear": now.month == 1 and now.day 
    })

Desktop/Website-Project-Coding/Django_edx_learning/namvt/task/views.py
from django.http.response import HttpResponseRedirect
from django.shortcuts import render
from django.http import HttpResponse
from django import forms
from django.http import HttpResponseRedirect
from django.urls import reverse

#tasks = ["foo", "bar", "baz"]

class NewTaskForm(forms.Form):
    task1 = forms.CharField(label="New Task")
    #Priority = forms.IntegerField(min_value=1, max_value=10)


# Create your views here.
def index(request):
    if "tasks" not in request.session:
        request.session["tasks"]= []
    return render(request, "task/index.html",{
        "task": request.session["tasks"]
    })

def add(request):
    if request.method == "POST":
        form = NewTaskForm(request.POST)
        if form.is_valid():
            task = form.cleaned_data["task1"]
            request.session["tasks"] += [task]
            return HttpResponseRedirect(reverse("task:index"))
        else:
            return render(request, "task/add.html", {
                "form":form
            })

    return render(request, "task/add.html", {
        "form": NewTaskForm()
    })

Desktop/Website-Project-Coding/Django_edx_learning/namvt/hello/templates/hello/greet.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Hello, {{ name }}!</h1>
</body>
</html>

Desktop/Website-Project-Coding/Django_edx_learning/namvt/hello/templates/hello/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Hello, world</h1>
</body>
</html>

Desktop/Website-Project-Coding/Django_edx_learning/namvt/newyear/templates/newyear/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'newyear/style.css' %}">
</head>
<body>
    {% if newyear %}
        <h1>YES</h1>
    {% else %}
        <h1>NO</h1>
    {% endif %}
</body>
</html>

Desktop/Website-Project-Coding/Django_edx_learning/namvt/task/templates/task/add.html
{% extends "task/layout.html" %}

{% block body %}
    <h1>Add</h1>
    <form action="{% url 'task:add' %}" method="POST">
        {% csrf_token %}
        {{ form }}
        <input type="submit">
    </form>
    <a href="{% url 'task:index' %}">View Task</a>
{% endblock %}

Desktop/Website-Project-Coding/Django_edx_learning/namvt/task/templates/task/index.html
{% extends "task/layout.html" %}

{% block body %}
    <h1>Task</h1>
    <ul>
        {% for task in task %}
            <li>{{task}}</li>
        {% empty %}
            <li>No tasks.</li>
        {% endfor %}
    </ul>
    <a href="{% url 'task:add' %}">Add a new task</a>
{% endblock %}

Desktop/Website-Project-Coding/Django_edx_learning/namvt/task/templates/task/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>hahahah</h1>
    {% block body %}

    {% endblock %}
</body>
</html>